### ISSUE TITLE
API key not persistent ?

### ISSUE THREAD

**Issue by Monsluxe** [GrimOutlaw/ChatGPT-Bypass#5]
Hi eryone , while testing the code repo on both a Mac, and a Kali Linux machine it appears I need to re export the API key at every startup, I now managed to do it automatically but, not very convenient isn't it ?

Bravo for y'all project and thx for what y'all are doing for this code repo

**Comment by Monsluxe** [comment]
jq: error (at <stdin>:8): Cannot iterate over null (null)

here is my output after a reboot if i did not re-exported the key

**Comment by AndrijaRD** [comment]
I am having the same issue:
$ q: error (at <stdin>:8): Cannot iterate over null (null)
and i am running on kali linux.

After cloning i did following:
1. cd cd ChatGPT-Bypass
2. chmod +x chatgpt_bypass.sh
3. export CHATGPT_TOKEN=sk-GtubLi...
4. sudo ./chatgpt_bypass.sh "What is your name" (for example)
How do i fix it?

**Comment by AndrijaRD** [comment]
> I am having the same issue: $ q: error (at :8): Cannot iterate over null (null) and i am running on kali linux.
> 
> After cloning i did the following:
> 
> 1. cd ChatGPT-Bypass
> 2. chmod +x chatgpt_bypass.sh
> 3. export CHATGPT_TOKEN=sk-GtubLi...
> 4. sudo ./chatgpt_bypass.sh "What is your name" (for example)
> 
> How do i fix it?

Update: I fixed it
i did **nano chatgpt_bypass.sh** and then where is say **Authorization: Bearer $CHATGPT_TOKEN** i replaced $CHATGPT_TOKEN with my chat-gpt token.

**Comment by GrimOutlaw** [comment]
You can also set the CHATGPT_TOKEN as a variable in your shell rc file; ie bashrc, etc.
